# Calculo-de-ano-em-Python
PER= int(input("Digite o percentual:"))
NOME= input("Digite o seu nome:")
IDADE= int(input("Digite sua idade:"))
ANO=int(2023-19)
print("O ano que você nasceu é",2023-IDADE)
print(NOME,"o ano que você nasceu é",2023-IDADE)
SALDO= float(input ("Digite seu saldo:"))
print (NOME,"O seu saldo é: ",SALDO)
print(f"O seu saldo com {PER} é: ,{SALDO*PER/100+SALDO}")
print(f"Você:{NOME} que nasceu em:{ANO} terá um saldo de {PER}%, que será de R${SALDO+PER}")
